### ISSUE TITLE
ZC or CZ?

### ISSUE THREAD

**Issue by YuhuiMa** [panji1990/Deep-subspace-clustering-networks#15]
Hi, 
In your paper,  the self-expressiveness property is defined as ||Z-ZC||. However, in your code, such as:
z_c = tf.matmul(Coef,z)
this seems to refer to CZ rather than ZC, right?

**Comment by panji530** [comment]
It depends on how data is organized. If the data is stored column-wise, we use ZC; if row-wise, we use CZ. For python, the default matrix data format is row-wise, so we use CZ.

**Comment by chenxofhit** [comment]
@panji1990 I do not know if I am right, for the summary architecture of the neural network, the input to the algorithm is a matrix in the form [feature, sample],  and in the first layer the neuron nodes number is #sample, and then the second and later layer the neuron nodes number is  ${some ratio} * #sample if   ${some ratio}  exist,  the neuron nodes number in the last layer of the encoder goes back to #sample and then comes the self-expression layer, which also has #sample neurons. As a result, the parameters between the last encoder layer to the self-expression layer are #sample * #sample due to the fully connected way?
